data_path:  /home/patrick/github/data/liftout/train-new/train
label_path: /home/patrick/github/data/liftout/train-new/train/labels 
save_path: /home/patrick/github/fibsem/fibsem/segmentation/models/autoliftout/new-base/e20/
checkpoint: null #/home/patrick/github/fibsem/fibsem/segmentation/models/openfibsem-baseline-34.pt 
encoder: "resnet34" 
epochs: 30
batch_size: 4 
num_classes: 3 
lr: 3.0e-4
wandb: true 
wandb_project: "autoliftout"
wandb_entity: "demarcolab"
