data_paths:  [/home/patrick/github/data/liftout/train-waffle/train]
label_paths: [/home/patrick/github/data/liftout/train-waffle/train/labels ]
save_path: /home/patrick/github/fibsem/fibsem/segmentation/models/autoliftout/waffle/aug/finetune
checkpoint: /home/patrick/github/fibsem/fibsem/segmentation/models/autoliftout/aug/base/combo/model24.pt
encoder: "resnet50" 
epochs: 20
batch_size: 2 
num_classes: 3 
lr: 3.0e-4
wandb: true 
wandb_project: "autoliftout"
wandb_entity: "demarcolab"
