CLASS_COLORS = {
    0: "black",
    1: "red",
    2: "green",
    3: "cyan",
    4: "yellow",
    5: "magenta",
    6: "blue",
    7: "white",
    8: "orange",
    9: "purple",
    10: "pink",
    11: "brown",
    12: "gray",
    13: "olive",
    14: "maroon",
    15: "navy",
    16: "teal",
    17: "lime",
    18: "aqua",
    19: "silver",
    20: "gold",
    21: "indigo",
    22: "violet",
    23: "turquoise",
    24: "tan",
    25: "orchid",
    26: "salmon",
    27: "khaki",
    28: "coral",
    29: "crimson",
    30: "plum",
    31: "lavender",
    32: "darkgreen",
    33: "darkblue",
    34: "darkred",
    35: "darkgray",
    36: "darkorange",
}

import os
CONFIG_PATH = os.path.join(os.path.dirname(__file__), "config.yml")