labelling:
  raw_dir: "change\\this\\path"
  data_dir: "change\\this\\path"
train:
  data_dir: "change\\this\\path"
  save_dir: "change\\this\\path"
  wandb: true # Logs information and plots to wandb
  checkpoint: null # Path to model if you would like to resume training
  encoder: "resnet18" # Specify model architecture. List of available encoders in readme.
  epochs: 10 # Number of epochs to train for
  cuda: true # Enable/Disable CUDA training
  batch_size: 1 # Number of batches per epoch
  num_classes: 3 # Number of classes in segmentation labels. Includes background as class 0.
  optimizer: "Adam" # Adam or SGD, not case sensitive
  learning_rate: 0.0001
  wandb_project: "fibsem_pipeline"
  wandb_entity: "demarcolab"
inference:
  data_dir: "change\\this\\path"
  model_dir: "change\\this\\path"
  output_dir: "change\\this\\path"
  wandb: true
  cuda: false
  encoder: "resnet18"
  num_classes: 3
  wandb_project: "add project"
  wandb_entity: "add entity"

