labelling:
  raw_dir: "C:\\Users\\lachl\\OneDrive\\Desktop\\DeMarco\\raw_img"
  data_dir: "C:\\Users\\lachl\\OneDrive\\Desktop\\DeMarco\\data_img"
train:
  data_dir: "C:\\Users\\lachl\\OneDrive\\Desktop\\DeMarco\\data_img"
  save_dir: "fibsem\\segmentation\\models"
  wandb: true # Logs information and plots to wandb
  checkpoint: null # Path to model if you would like to resume training
  encoder: "resnet18" # Specify model architecture. List of available encoders in readme.
  epochs: 10 # Number of epochs to train for
  cuda: false # Enable/Disable CUDA training
  batch_size: 1 # Number of batches per epoch
  num_classes: 3 # Number of classes in segmentation labels. Includes background as class 0.
  optimizer: "Adam" # Adam or SGD, not case sensitive
  learning_rate: 0.0001
  wandb_project: "fibsem_pipeline"
  wandb_entity: "demarcolab"
inference:
  data_dir: "change\\this\\path"
  model_dir: "fibsem\\segmentation\\models"
  output_dir: "fibsem\\segmentation\\outputs"
  wandb: false
  cuda: false
  encoder: "resnet18"
  num_classes: 3
  wandb_project: "fibsem_pipeline"
  wandb_entity: "demarcolab"

