CLASS_COLORS:
  0: "black"
  1: "red"
  2: "green"
  3: "cyan"
  4: "yellow"
  5: "magenta"
  6: "purple"
  7: "white"
  8: "orange"
  9: "blue"
  10: "pink"
  11: "gold"
  12: "salmon"
  13: "olive"
  14: "maroon"
  15: "navy"
  16: "teal"
  17: "lime"
  18: "aqua"
  19: "silver"
  20: "brown"
  21: "indigo"
  22: "violet"
  23: "turquoise"
  24: "tan"
  25: "orchid"
  26: "gray"
  27: "khaki"
  28: "coral"
  29: "crimson"
  30: "plum"
  31: "lavender"
  32: "darkgreen"
  33: "darkblue"
  34: "darkred"
  35: "darkgray"
  36: "darkorange"

CLASS_LABELS: # autolamella
  0: "background"
  1: "lamella"
  2: "manipulator"
  3: "landing_post"
  4: "copper_adaptor"
  5: "volume_block"


# CLASS_LABELS: # spacetomo
#   0: "background"
#   1: "white"
#   2: "black"
#   3: "crack"
#   4: "coating"
#   5: "cell"
#   6: "cellwall"
#   7: "nucleus"
#   8: "vacuole"
#   9: "mitos"
#   10: "lipiddroplets"
#   11: "vesicles"
#   12: "multivesicles"
#   13: "membranes"
#   14: "dynabeads"
#   15: "ice"
#   16: "cryst"
