name: fibsem
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.9
  - zarr
  - dask
  - tifffile
  - numpy
  - scipy
  - opencv
  - scikit-image
  - tqdm
  - matplotlib
  - napari
  - pytest
  - mypy
  - pip
  - pytorch
  - torchvision
  - cudatoolkit
  - segmentation-models-pytorch
