name: fibsem
channels:
  - conda-forge
dependencies:
  - python=3.9
  - zarr
  - dask
  - tifffile
  - numpy
  - scipy
  - opencv
  - scikit-image
  - tqdm
  - matplotlib
  - napari
  - scikit-image
  - pytest
  - mypy
  - pip
  - git
