data_path: "/home/patrick/github/data/autolamella-paper/model-development/train/liftout/test/keypoints.csv"    # test data csv
images_path: "/home/patrick/github/data/autolamella-paper/model-development/train/liftout/test"                 # test data image directory
save_path: "/home/patrick/github/data/autolamella-paper/model-development/eval/hf-mega-eval/liftout/keypoint-eval"        # save path for evaluation results

checkpoints: # list of checkpoints to evaluate
  - checkpoint: autolamella-liftout-20240107.pt
  - checkpoint: autolamella-mega-20240107.pt
  - checkpoint: patrickcleeve/segformer-b1-autolamella-mega-1

# plot 
thresholds:
- 250
- 100
- 50
- 25
- 10

# options
run_eval: True
plot_eval: True

show_det_plot: False
save_det_plot: True
show_eval_plot: False
save_eval_plot: True