data_path: "eval/autolamella-waffle/data.csv"   # test data csv
images_path: "eval/autolamella-waffle/images"   # test images
save_path: "eval/autolamella-waffle/eval"       # save path for evaluation results

checkpoints:
  - checkpoint: "openfibsem-baseline-34.pt"
    encoder: "resnet34"
    nc: 3
  - checkpoint: "autolamella-02-34.pt"
    encoder: "resnet34"
    nc: 3
  - checkpoint: "autolamella-04-34.pt"
    encoder: "resnet34"
    nc: 3
  - checkpoint: "autolamella-05-34.pt"
    encoder: "resnet34"
    nc: 3

# plot
thresholds:
- 250
- 100
- 50
- 25
- 10

# options
run_eval: True
plot_eval: True

show_det_plot: False
save_det_plot: True
show_eval_plot: False
save_eval_plot: True