# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev797+g191aa4d.d20230227'
__version_tuple__ = version_tuple = (0, 1, 'dev797', 'g191aa4d.d20230227')
