# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev853+g59f42e0.d20230307'
__version_tuple__ = version_tuple = (0, 1, 'dev853', 'g59f42e0.d20230307')
