electron:
    enabled: true
gis:
    enabled: true
    multichem: true
ion:
    enabled: true
manipulator:
    enabled: true
    positions:
        calibrated: true
        parking:
            x: -0.008918395
            y: 0.0006548000000000001
            z: -0.004848865
        standby:
            x: 0.0
            y: 0.0
            z: 0.00545
        working:
            x: 0.0
            y: 0.0
            z: 0.00585
    rotation: false
    tilt: false
stage:
    enabled: true
    rotation: true
    tilt: true
system:
    description: FIBSEM
    id: 0
    manufacturer: Demo
    name: FIBSEM
    version: '0.1'
