electron:
    enabled: true
gis:
    enabled: true
    multichem: true
ion:
    enabled: true
manipulator:
    enabled: true
    positions:
        parking:
            x: 3.14
            y: 2
            z: 3
        standby:
            x: 4
            y: 5
            z: 6
        working:
            x: 7
            y: 8
            z: 9
    rotation: true
    tilt: true
stage:
    enabled: true
    rotation: true
    tilt: true
system:
    description: FIBSEM
    id: 0
    manufacturer: Demo
    name: FIBSEM
    version: '0.1'
