system:
    application_file: autolamella
    electron:
        current: 1.0e-12
        detector_mode: SecondaryElectrons
        detector_type: ETD
        eucentric_height: 0.004
        plasma_gas: null
        voltage: 2000.0
    ion:
        current: 2.0e-11
        detector_mode: SecondaryElectrons
        detector_type: ETD
        eucentric_height: 0.0165
        plasma_gas: Argon
        voltage: 30000.0
    ip_address: 10.0.0.1
    stage:
        needle_stage_height_limit: 3.7
        pre_tilt: 35
        rotation_flat_to_electron: 50
        rotation_flat_to_ion: 230
        tilt_flat_to_electron: 35
        tilt_flat_to_ion: 52
user:
    autocontrast: true
    dwell_time: 1.0e-06
    gamma:
        enabled: true
        max_gamma: 2.0
        min_gamma: 0.0
        scale_factor: 0.1
        threshold: 45
    hfw: 0.00015
    label: null
    resolution: 2048x1768
    save: false
    save_path: null
