# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OpenLMCorrelationWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(461, 300)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget_cpoints = QtWidgets.QTableWidget(self.frame)
        self.tableWidget_cpoints.setMinimumSize(QtCore.QSize(423, 0))
        self.tableWidget_cpoints.setShowGrid(True)
        self.tableWidget_cpoints.setObjectName("tableWidget_cpoints")
        self.tableWidget_cpoints.setColumnCount(4)
        self.tableWidget_cpoints.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_cpoints.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_cpoints.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_cpoints.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_cpoints.setHorizontalHeaderItem(3, item)
        self.verticalLayout.addWidget(self.tableWidget_cpoints)
        self.pushButton_correlate = QtWidgets.QPushButton(self.frame)
        self.pushButton_correlate.setObjectName("pushButton_correlate")
        self.verticalLayout.addWidget(self.pushButton_correlate)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.tableWidget_cpoints.horizontalHeaderItem(0)
        item.setText(_translate("Form", "x1"))
        item = self.tableWidget_cpoints.horizontalHeaderItem(1)
        item.setText(_translate("Form", "y1"))
        item = self.tableWidget_cpoints.horizontalHeaderItem(2)
        item.setText(_translate("Form", "x2"))
        item = self.tableWidget_cpoints.horizontalHeaderItem(3)
        item.setText(_translate("Form", "y2"))
        self.pushButton_correlate.setText(_translate("Form", "Correlate"))
