# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'connect_napari.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1110, 1079)
        self.connect_microscope = QtWidgets.QPushButton(Dialog)
        self.connect_microscope.setGeometry(QtCore.QRect(330, 80, 281, 23))
        self.connect_microscope.setObjectName("connect_microscope")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.connect_microscope.setText(_translate("Dialog", "connect to microscope"))
