# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CurrentAlignmentWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WizardPage(object):
    def setupUi(self, WizardPage):
        WizardPage.setObjectName("WizardPage")
        WizardPage.resize(373, 484)
        self.gridLayout = QtWidgets.QGridLayout(WizardPage)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(WizardPage)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.comboBox_ref_current = QtWidgets.QComboBox(WizardPage)
        self.comboBox_ref_current.setObjectName("comboBox_ref_current")
        self.gridLayout.addWidget(self.comboBox_ref_current, 3, 1, 1, 1)
        self.pushButton_align_beam = QtWidgets.QPushButton(WizardPage)
        self.pushButton_align_beam.setObjectName("pushButton_align_beam")
        self.gridLayout.addWidget(self.pushButton_align_beam, 6, 0, 1, 2)
        self.comboBox_aligned_current = QtWidgets.QComboBox(WizardPage)
        self.comboBox_aligned_current.setObjectName("comboBox_aligned_current")
        self.gridLayout.addWidget(self.comboBox_aligned_current, 4, 1, 1, 1)
        self.label = QtWidgets.QLabel(WizardPage)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(WizardPage)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.checkBox_overlay = QtWidgets.QCheckBox(WizardPage)
        self.checkBox_overlay.setObjectName("checkBox_overlay")
        self.gridLayout.addWidget(self.checkBox_overlay, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 2)
        self.pushButton_take_images = QtWidgets.QPushButton(WizardPage)
        self.pushButton_take_images.setObjectName("pushButton_take_images")
        self.gridLayout.addWidget(self.pushButton_take_images, 5, 0, 1, 2)
        self.listdone = QtWidgets.QPlainTextEdit(WizardPage)
        self.listdone.setObjectName("listdone")
        self.gridLayout.addWidget(self.listdone, 7, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 8, 0, 1, 2)

        self.retranslateUi(WizardPage)
        QtCore.QMetaObject.connectSlotsByName(WizardPage)

    def retranslateUi(self, WizardPage):
        _translate = QtCore.QCoreApplication.translate
        WizardPage.setWindowTitle(_translate("WizardPage", "WizardPage"))
        self.label_3.setText(_translate("WizardPage", "Aligned Current (Right):"))
        self.pushButton_align_beam.setText(_translate("WizardPage", "Align Beam"))
        self.label.setText(_translate("WizardPage", "FIB Current alignment"))
        self.label_2.setText(_translate("WizardPage", "Reference Current (Left):"))
        self.checkBox_overlay.setText(_translate("WizardPage", "Overlay Images"))
        self.pushButton_take_images.setText(_translate("WizardPage", "Take Images"))
