# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FibsemUI2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(319, 620)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_system = QtWidgets.QWidget()
        self.tab_system.setObjectName("tab_system")
        self.gridLayout_system = QtWidgets.QGridLayout(self.tab_system)
        self.gridLayout_system.setObjectName("gridLayout_system")
        self.tabWidget.addTab(self.tab_system, "")
        self.tab_imaging = QtWidgets.QWidget()
        self.tab_imaging.setObjectName("tab_imaging")
        self.gridLayout_imaging = QtWidgets.QGridLayout(self.tab_imaging)
        self.gridLayout_imaging.setObjectName("gridLayout_imaging")
        self.tabWidget.addTab(self.tab_imaging, "")
        self.tab_movement = QtWidgets.QWidget()
        self.tab_movement.setObjectName("tab_movement")
        self.gridLayout_movement = QtWidgets.QGridLayout(self.tab_movement)
        self.gridLayout_movement.setObjectName("gridLayout_movement")
        self.tabWidget.addTab(self.tab_movement, "")
        self.tab_tools = QtWidgets.QWidget()
        self.tab_tools.setObjectName("tab_tools")
        self.gridLayout_tools = QtWidgets.QGridLayout(self.tab_tools)
        self.gridLayout_tools.setObjectName("gridLayout_tools")
        self.tabWidget.addTab(self.tab_tools, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 319, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "OpenFIBSEM"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_system), _translate("MainWindow", "System"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_imaging), _translate("MainWindow", "Imaging"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_movement), _translate("MainWindow", "Movement"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_tools), _translate("MainWindow", "Tools"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
