# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FibsemBBoxLabelling.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.label_data_config = QtWidgets.QLabel(Form)
        self.label_data_config.setObjectName("label_data_config")
        self.gridLayout.addWidget(self.label_data_config, 3, 0, 1, 1)
        self.pushButton_add_mode = QtWidgets.QPushButton(Form)
        self.pushButton_add_mode.setObjectName("pushButton_add_mode")
        self.gridLayout.addWidget(self.pushButton_add_mode, 7, 0, 1, 1)
        self.lineEdit_data_path = QtWidgets.QLineEdit(Form)
        self.lineEdit_data_path.setObjectName("lineEdit_data_path")
        self.gridLayout.addWidget(self.lineEdit_data_path, 1, 1, 1, 1)
        self.pushButton_data_path = QtWidgets.QToolButton(Form)
        self.pushButton_data_path.setObjectName("pushButton_data_path")
        self.gridLayout.addWidget(self.pushButton_data_path, 1, 2, 1, 1)
        self.lineEdit_labels_path = QtWidgets.QLineEdit(Form)
        self.lineEdit_labels_path.setObjectName("lineEdit_labels_path")
        self.gridLayout.addWidget(self.lineEdit_labels_path, 2, 1, 1, 1)
        self.pushButton_data_config = QtWidgets.QToolButton(Form)
        self.pushButton_data_config.setObjectName("pushButton_data_config")
        self.gridLayout.addWidget(self.pushButton_data_config, 3, 2, 1, 1)
        self.label_data_path = QtWidgets.QLabel(Form)
        self.label_data_path.setObjectName("label_data_path")
        self.gridLayout.addWidget(self.label_data_path, 1, 0, 1, 1)
        self.pushButton_edit_mode = QtWidgets.QPushButton(Form)
        self.pushButton_edit_mode.setObjectName("pushButton_edit_mode")
        self.gridLayout.addWidget(self.pushButton_edit_mode, 7, 1, 1, 2)
        self.label_class_map = QtWidgets.QLabel(Form)
        self.label_class_map.setObjectName("label_class_map")
        self.gridLayout.addWidget(self.label_class_map, 6, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 9, 0, 1, 3)
        self.label_data_file_ext = QtWidgets.QLabel(Form)
        self.label_data_file_ext.setObjectName("label_data_file_ext")
        self.gridLayout.addWidget(self.label_data_file_ext, 4, 0, 1, 1)
        self.label_title = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.gridLayout.addWidget(self.label_title, 0, 0, 1, 3)
        self.label_labels_path = QtWidgets.QLabel(Form)
        self.label_labels_path.setObjectName("label_labels_path")
        self.gridLayout.addWidget(self.label_labels_path, 2, 0, 1, 1)
        self.pushButton_labels_path = QtWidgets.QToolButton(Form)
        self.pushButton_labels_path.setObjectName("pushButton_labels_path")
        self.gridLayout.addWidget(self.pushButton_labels_path, 2, 2, 1, 1)
        self.lineEdit_data_config = QtWidgets.QLineEdit(Form)
        self.lineEdit_data_config.setObjectName("lineEdit_data_config")
        self.gridLayout.addWidget(self.lineEdit_data_config, 3, 1, 1, 1)
        self.comboBox_data_file_ext = QtWidgets.QComboBox(Form)
        self.comboBox_data_file_ext.setObjectName("comboBox_data_file_ext")
        self.gridLayout.addWidget(self.comboBox_data_file_ext, 4, 1, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 5, 0, 1, 3)
        self.label_instructions = QtWidgets.QLabel(Form)
        self.label_instructions.setObjectName("label_instructions")
        self.gridLayout.addWidget(self.label_instructions, 8, 0, 1, 3)
        self.comboBox_class_map = QtWidgets.QComboBox(Form)
        self.comboBox_class_map.setObjectName("comboBox_class_map")
        self.gridLayout.addWidget(self.comboBox_class_map, 6, 1, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_data_config.setText(_translate("Form", "Class Config"))
        self.pushButton_add_mode.setText(_translate("Form", "Add"))
        self.pushButton_data_path.setText(_translate("Form", "..."))
        self.pushButton_data_config.setText(_translate("Form", "..."))
        self.label_data_path.setText(_translate("Form", "Image Path"))
        self.pushButton_edit_mode.setText(_translate("Form", "Edit"))
        self.label_class_map.setText(_translate("Form", "Class Map"))
        self.label_data_file_ext.setText(_translate("Form", "File Extension"))
        self.label_title.setText(_translate("Form", "OpenFIBSEM BBox Labelling"))
        self.label_labels_path.setText(_translate("Form", "Label Path"))
        self.pushButton_labels_path.setText(_translate("Form", "..."))
        self.label_instructions.setText(_translate("Form", "Instructions"))
