# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FibsemToolsWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 307)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.label_tools_utils_header = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_tools_utils_header.setFont(font)
        self.label_tools_utils_header.setObjectName("label_tools_utils_header")
        self.gridLayout.addWidget(self.label_tools_utils_header, 0, 0, 1, 1)
        self.pushButton_sputter_multichem = QtWidgets.QPushButton(Form)
        self.pushButton_sputter_multichem.setObjectName("pushButton_sputter_multichem")
        self.gridLayout.addWidget(self.pushButton_sputter_multichem, 1, 0, 1, 1)
        self.pushButton_move_stage_out = QtWidgets.QPushButton(Form)
        self.pushButton_move_stage_out.setObjectName("pushButton_move_stage_out")
        self.gridLayout.addWidget(self.pushButton_move_stage_out, 2, 0, 1, 1)
        self.label_tools_calibration_header = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_tools_calibration_header.setFont(font)
        self.label_tools_calibration_header.setObjectName("label_tools_calibration_header")
        self.gridLayout.addWidget(self.label_tools_calibration_header, 3, 0, 1, 1)
        self.pushButton_auto_focus_beam = QtWidgets.QPushButton(Form)
        self.pushButton_auto_focus_beam.setObjectName("pushButton_auto_focus_beam")
        self.gridLayout.addWidget(self.pushButton_auto_focus_beam, 4, 0, 1, 1)
        self.pushButton_auto_discharge_beam = QtWidgets.QPushButton(Form)
        self.pushButton_auto_discharge_beam.setObjectName("pushButton_auto_discharge_beam")
        self.gridLayout.addWidget(self.pushButton_auto_discharge_beam, 5, 0, 1, 1)
        self.pushButton_auto_home_stage = QtWidgets.QPushButton(Form)
        self.pushButton_auto_home_stage.setObjectName("pushButton_auto_home_stage")
        self.gridLayout.addWidget(self.pushButton_auto_home_stage, 6, 0, 1, 1)
        self.pushButton_auto_link_stage = QtWidgets.QPushButton(Form)
        self.pushButton_auto_link_stage.setObjectName("pushButton_auto_link_stage")
        self.gridLayout.addWidget(self.pushButton_auto_link_stage, 7, 0, 1, 1)
        self.pushButton_auto_needle_calibration = QtWidgets.QPushButton(Form)
        self.pushButton_auto_needle_calibration.setObjectName("pushButton_auto_needle_calibration")
        self.gridLayout.addWidget(self.pushButton_auto_needle_calibration, 8, 0, 1, 1)
        self.label_tools_validation_header = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_tools_validation_header.setFont(font)
        self.label_tools_validation_header.setObjectName("label_tools_validation_header")
        self.gridLayout.addWidget(self.label_tools_validation_header, 9, 0, 1, 1)
        self.pushButton_validate_microscope_settings = QtWidgets.QPushButton(Form)
        self.pushButton_validate_microscope_settings.setObjectName("pushButton_validate_microscope_settings")
        self.gridLayout.addWidget(self.pushButton_validate_microscope_settings, 10, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_tools_utils_header.setText(_translate("Form", "Utilities"))
        self.pushButton_sputter_multichem.setText(_translate("Form", "Sputter MultiChem"))
        self.pushButton_move_stage_out.setText(_translate("Form", "Move Stage Out"))
        self.label_tools_calibration_header.setText(_translate("Form", "Calibration"))
        self.pushButton_auto_focus_beam.setText(_translate("Form", "Auto Focus"))
        self.pushButton_auto_discharge_beam.setText(_translate("Form", "Auto Discharge"))
        self.pushButton_auto_home_stage.setText(_translate("Form", "Auto Home"))
        self.pushButton_auto_link_stage.setText(_translate("Form", "Auto Link"))
        self.pushButton_auto_needle_calibration.setText(_translate("Form", "Auto Needle Calibration"))
        self.label_tools_validation_header.setText(_translate("Form", "Validation"))
        self.pushButton_validate_microscope_settings.setText(_translate("Form", "Validate Microscope Settings"))
