# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FibsemSpotBurnWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(332, 202)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_information = QtWidgets.QLabel(Form)
        self.label_information.setText("")
        self.label_information.setObjectName("label_information")
        self.gridLayout_2.addWidget(self.label_information, 4, 1, 1, 2)
        self.label_beam_current = QtWidgets.QLabel(Form)
        self.label_beam_current.setObjectName("label_beam_current")
        self.gridLayout_2.addWidget(self.label_beam_current, 3, 1, 1, 1)
        self.label_exposure_time = QtWidgets.QLabel(Form)
        self.label_exposure_time.setObjectName("label_exposure_time")
        self.gridLayout_2.addWidget(self.label_exposure_time, 2, 1, 1, 1)
        self.doubleSpinBox_exposure_time = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox_exposure_time.setObjectName("doubleSpinBox_exposure_time")
        self.gridLayout_2.addWidget(self.doubleSpinBox_exposure_time, 2, 2, 1, 1)
        self.comboBox_beam_current = QtWidgets.QComboBox(Form)
        self.comboBox_beam_current.setObjectName("comboBox_beam_current")
        self.gridLayout_2.addWidget(self.comboBox_beam_current, 3, 2, 1, 1)
        self.pushButton_run_spot_burn = QtWidgets.QPushButton(Form)
        self.pushButton_run_spot_burn.setObjectName("pushButton_run_spot_burn")
        self.gridLayout_2.addWidget(self.pushButton_run_spot_burn, 6, 1, 1, 2)
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_2.addWidget(self.progressBar, 5, 1, 1, 2)
        self.label_title = QtWidgets.QLabel(Form)
        self.label_title.setObjectName("label_title")
        self.gridLayout_2.addWidget(self.label_title, 1, 1, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 7, 1, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_beam_current.setText(_translate("Form", "Beam Current"))
        self.label_exposure_time.setText(_translate("Form", "Exposure Time"))
        self.pushButton_run_spot_burn.setText(_translate("Form", "Run Spot Burn"))
        self.label_title.setText(_translate("Form", "Spot Burn"))
