# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FibsemSegmentationModelWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_checkpoint = QtWidgets.QLineEdit(Form)
        self.lineEdit_checkpoint.setObjectName("lineEdit_checkpoint")
        self.gridLayout.addWidget(self.lineEdit_checkpoint, 2, 1, 1, 1)
        self.lineEdit_encoder = QtWidgets.QLineEdit(Form)
        self.lineEdit_encoder.setObjectName("lineEdit_encoder")
        self.gridLayout.addWidget(self.lineEdit_encoder, 1, 1, 1, 1)
        self.label_encoder = QtWidgets.QLabel(Form)
        self.label_encoder.setObjectName("label_encoder")
        self.gridLayout.addWidget(self.label_encoder, 1, 0, 1, 1)
        self.spinBox_num_classes = QtWidgets.QSpinBox(Form)
        self.spinBox_num_classes.setObjectName("spinBox_num_classes")
        self.gridLayout.addWidget(self.spinBox_num_classes, 3, 1, 1, 1)
        self.label_header_model = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_header_model.setFont(font)
        self.label_header_model.setObjectName("label_header_model")
        self.gridLayout.addWidget(self.label_header_model, 0, 0, 1, 2)
        self.label_checkpoint = QtWidgets.QLabel(Form)
        self.label_checkpoint.setObjectName("label_checkpoint")
        self.gridLayout.addWidget(self.label_checkpoint, 2, 0, 1, 1)
        self.label_num_classes = QtWidgets.QLabel(Form)
        self.label_num_classes.setObjectName("label_num_classes")
        self.gridLayout.addWidget(self.label_num_classes, 3, 0, 1, 1)
        self.pushButton_load_model = QtWidgets.QPushButton(Form)
        self.pushButton_load_model.setObjectName("pushButton_load_model")
        self.gridLayout.addWidget(self.pushButton_load_model, 4, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_encoder.setText(_translate("Form", "Encoder"))
        self.label_header_model.setText(_translate("Form", "Segmentation Model"))
        self.label_checkpoint.setText(_translate("Form", "Checkpoint"))
        self.label_num_classes.setText(_translate("Form", "No. Classes"))
        self.pushButton_load_model.setText(_translate("Form", "Load Model"))
