# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FibsemDetectionWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 305)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.label_info = QtWidgets.QLabel(Form)
        self.label_info.setMinimumSize(QtCore.QSize(0, 150))
        self.label_info.setText("")
        self.label_info.setObjectName("label_info")
        self.gridLayout.addWidget(self.label_info, 3, 0, 1, 2)
        self.label_feature = QtWidgets.QLabel(Form)
        self.label_feature.setObjectName("label_feature")
        self.gridLayout.addWidget(self.label_feature, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 7, 0, 1, 2)
        self.pushButton_continue = QtWidgets.QPushButton(Form)
        self.pushButton_continue.setObjectName("pushButton_continue")
        self.gridLayout.addWidget(self.pushButton_continue, 5, 0, 1, 2)
        self.checkBox_show_mask = QtWidgets.QCheckBox(Form)
        self.checkBox_show_mask.setObjectName("checkBox_show_mask")
        self.gridLayout.addWidget(self.checkBox_show_mask, 2, 0, 1, 1)
        self.label_title = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.gridLayout.addWidget(self.label_title, 0, 0, 1, 2)
        self.comboBox_feature = QtWidgets.QComboBox(Form)
        self.comboBox_feature.setObjectName("comboBox_feature")
        self.gridLayout.addWidget(self.comboBox_feature, 1, 1, 1, 1)
        self.label_instructions = QtWidgets.QLabel(Form)
        self.label_instructions.setWordWrap(True)
        self.label_instructions.setObjectName("label_instructions")
        self.gridLayout.addWidget(self.label_instructions, 4, 0, 1, 2)
        self.pushButton_test_function = QtWidgets.QPushButton(Form)
        self.pushButton_test_function.setObjectName("pushButton_test_function")
        self.gridLayout.addWidget(self.pushButton_test_function, 6, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_feature.setText(_translate("Form", "Feature"))
        self.pushButton_continue.setText(_translate("Form", "Continue"))
        self.checkBox_show_mask.setText(_translate("Form", "Show Mask"))
        self.label_title.setText(_translate("Form", "Feature Detection"))
        self.label_instructions.setText(_translate("Form", "Select the feature, and click to change the feature position."))
        self.pushButton_test_function.setText(_translate("Form", "TEST"))
