# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FibsemTileWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 8, 0, 1, 2)
        self.label_tile_overlap = QtWidgets.QLabel(Form)
        self.label_tile_overlap.setObjectName("label_tile_overlap")
        self.gridLayout.addWidget(self.label_tile_overlap, 4, 0, 1, 1)
        self.label_tile_grid_size = QtWidgets.QLabel(Form)
        self.label_tile_grid_size.setObjectName("label_tile_grid_size")
        self.gridLayout.addWidget(self.label_tile_grid_size, 2, 0, 1, 1)
        self.pushButton_run_tile_collection = QtWidgets.QPushButton(Form)
        self.pushButton_run_tile_collection.setObjectName("pushButton_run_tile_collection")
        self.gridLayout.addWidget(self.pushButton_run_tile_collection, 5, 0, 1, 2)
        self.comboBox_tile_beam_type = QtWidgets.QComboBox(Form)
        self.comboBox_tile_beam_type.setObjectName("comboBox_tile_beam_type")
        self.gridLayout.addWidget(self.comboBox_tile_beam_type, 1, 1, 1, 1)
        self.label_tile_beam_type = QtWidgets.QLabel(Form)
        self.label_tile_beam_type.setObjectName("label_tile_beam_type")
        self.gridLayout.addWidget(self.label_tile_beam_type, 1, 0, 1, 1)
        self.label_title = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.gridLayout.addWidget(self.label_title, 0, 0, 1, 2)
        self.lineEdit_tile_image_path = QtWidgets.QLineEdit(Form)
        self.lineEdit_tile_image_path.setObjectName("lineEdit_tile_image_path")
        self.gridLayout.addWidget(self.lineEdit_tile_image_path, 6, 0, 1, 2)
        self.label_tile_tile_size = QtWidgets.QLabel(Form)
        self.label_tile_tile_size.setObjectName("label_tile_tile_size")
        self.gridLayout.addWidget(self.label_tile_tile_size, 3, 0, 1, 1)
        self.doubleSpinBox_tile_grid_size = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox_tile_grid_size.setMaximum(1000000.0)
        self.doubleSpinBox_tile_grid_size.setProperty("value", 400.0)
        self.doubleSpinBox_tile_grid_size.setObjectName("doubleSpinBox_tile_grid_size")
        self.gridLayout.addWidget(self.doubleSpinBox_tile_grid_size, 2, 1, 1, 1)
        self.doubleSpinBox_tile_tile_size = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox_tile_tile_size.setMaximum(100000.0)
        self.doubleSpinBox_tile_tile_size.setProperty("value", 100.0)
        self.doubleSpinBox_tile_tile_size.setObjectName("doubleSpinBox_tile_tile_size")
        self.gridLayout.addWidget(self.doubleSpinBox_tile_tile_size, 3, 1, 1, 1)
        self.pushButton_load_image = QtWidgets.QPushButton(Form)
        self.pushButton_load_image.setObjectName("pushButton_load_image")
        self.gridLayout.addWidget(self.pushButton_load_image, 7, 0, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_tile_overlap.setText(_translate("Form", "Overlap (%)"))
        self.label_tile_grid_size.setText(_translate("Form", "Grid Size (um)"))
        self.pushButton_run_tile_collection.setText(_translate("Form", "Run Tile Collection"))
        self.label_tile_beam_type.setText(_translate("Form", "Beam Type"))
        self.label_title.setText(_translate("Form", "Tile Grid"))
        self.label_tile_tile_size.setText(_translate("Form", "Tile Size (um)"))
        self.pushButton_load_image.setText(_translate("Form", "Load Image"))
