# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FibsemMillingWidgetui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(363, 422)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.label_depth = QtWidgets.QLabel(Form)
        self.label_depth.setObjectName("label_depth")
        self.gridLayout.addWidget(self.label_depth, 13, 0, 1, 1)
        self.label_milling_current = QtWidgets.QLabel(Form)
        self.label_milling_current.setObjectName("label_milling_current")
        self.gridLayout.addWidget(self.label_milling_current, 1, 0, 1, 1)
        self.doubleSpinBox_dwell_time = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox_dwell_time.setMinimum(0.01)
        self.doubleSpinBox_dwell_time.setSingleStep(0.01)
        self.doubleSpinBox_dwell_time.setObjectName("doubleSpinBox_dwell_time")
        self.gridLayout.addWidget(self.doubleSpinBox_dwell_time, 6, 1, 1, 1)
        self.label_spot_size = QtWidgets.QLabel(Form)
        self.label_spot_size.setObjectName("label_spot_size")
        self.gridLayout.addWidget(self.label_spot_size, 5, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 15, 0, 1, 2)
        self.doubleSpinBox_centre_x = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox_centre_x.setMinimum(-1e+28)
        self.doubleSpinBox_centre_x.setMaximum(1e+18)
        self.doubleSpinBox_centre_x.setSingleStep(0.1)
        self.doubleSpinBox_centre_x.setObjectName("doubleSpinBox_centre_x")
        self.gridLayout.addWidget(self.doubleSpinBox_centre_x, 9, 1, 1, 1)
        self.doubleSpinBox_centre_y = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox_centre_y.setMinimum(-1e+16)
        self.doubleSpinBox_centre_y.setMaximum(1e+23)
        self.doubleSpinBox_centre_y.setSingleStep(0.1)
        self.doubleSpinBox_centre_y.setObjectName("doubleSpinBox_centre_y")
        self.gridLayout.addWidget(self.doubleSpinBox_centre_y, 10, 1, 1, 1)
        self.label_dwell_time = QtWidgets.QLabel(Form)
        self.label_dwell_time.setObjectName("label_dwell_time")
        self.gridLayout.addWidget(self.label_dwell_time, 6, 0, 1, 1)
        self.label_centre_x = QtWidgets.QLabel(Form)
        self.label_centre_x.setObjectName("label_centre_x")
        self.gridLayout.addWidget(self.label_centre_x, 9, 0, 1, 1)
        self.label_pattern = QtWidgets.QLabel(Form)
        self.label_pattern.setObjectName("label_pattern")
        self.gridLayout.addWidget(self.label_pattern, 8, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 16, 0, 1, 2)
        self.comboBox_application_file = QtWidgets.QComboBox(Form)
        self.comboBox_application_file.setObjectName("comboBox_application_file")
        self.gridLayout.addWidget(self.comboBox_application_file, 3, 1, 1, 1)
        self.comboBox_milling_current = QtWidgets.QComboBox(Form)
        self.comboBox_milling_current.setObjectName("comboBox_milling_current")
        self.gridLayout.addWidget(self.comboBox_milling_current, 1, 1, 1, 1)
        self.label_title = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.gridLayout.addWidget(self.label_title, 0, 0, 1, 2)
        self.label_centre_y = QtWidgets.QLabel(Form)
        self.label_centre_y.setObjectName("label_centre_y")
        self.gridLayout.addWidget(self.label_centre_y, 10, 0, 1, 1)
        self.label_width = QtWidgets.QLabel(Form)
        self.label_width.setObjectName("label_width")
        self.gridLayout.addWidget(self.label_width, 11, 0, 1, 1)
        self.comboBox_pattern = QtWidgets.QComboBox(Form)
        self.comboBox_pattern.setObjectName("comboBox_pattern")
        self.gridLayout.addWidget(self.comboBox_pattern, 8, 1, 1, 1)
        self.label_application_file = QtWidgets.QLabel(Form)
        self.label_application_file.setObjectName("label_application_file")
        self.gridLayout.addWidget(self.label_application_file, 3, 0, 1, 1)
        self.doubleSpinBox_spot_size = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox_spot_size.setMinimum(0.01)
        self.doubleSpinBox_spot_size.setSingleStep(0.01)
        self.doubleSpinBox_spot_size.setObjectName("doubleSpinBox_spot_size")
        self.gridLayout.addWidget(self.doubleSpinBox_spot_size, 5, 1, 1, 1)
        self.doubleSpinBox_depth = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox_depth.setMinimum(0.1)
        self.doubleSpinBox_depth.setMaximum(10000000000.0)
        self.doubleSpinBox_depth.setSingleStep(0.1)
        self.doubleSpinBox_depth.setProperty("value", 2.0)
        self.doubleSpinBox_depth.setObjectName("doubleSpinBox_depth")
        self.gridLayout.addWidget(self.doubleSpinBox_depth, 13, 1, 1, 1)
        self.label_height = QtWidgets.QLabel(Form)
        self.label_height.setObjectName("label_height")
        self.gridLayout.addWidget(self.label_height, 12, 0, 1, 1)
        self.doubleSpinBox_width = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox_width.setMinimum(0.1)
        self.doubleSpinBox_width.setMaximum(100000000000.0)
        self.doubleSpinBox_width.setSingleStep(0.1)
        self.doubleSpinBox_width.setProperty("value", 10.0)
        self.doubleSpinBox_width.setObjectName("doubleSpinBox_width")
        self.gridLayout.addWidget(self.doubleSpinBox_width, 11, 1, 1, 1)
        self.doubleSpinBox_height = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox_height.setMinimum(0.1)
        self.doubleSpinBox_height.setMaximum(100000000000000.0)
        self.doubleSpinBox_height.setSingleStep(0.1)
        self.doubleSpinBox_height.setProperty("value", 5.0)
        self.doubleSpinBox_height.setObjectName("doubleSpinBox_height")
        self.gridLayout.addWidget(self.doubleSpinBox_height, 12, 1, 1, 1)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 7, 0, 1, 2)
        self.label_hfw = QtWidgets.QLabel(Form)
        self.label_hfw.setObjectName("label_hfw")
        self.gridLayout.addWidget(self.label_hfw, 2, 0, 1, 1)
        self.doubleSpinBox_hfw = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox_hfw.setMinimum(10.0)
        self.doubleSpinBox_hfw.setMaximum(2700.0)
        self.doubleSpinBox_hfw.setProperty("value", 150.0)
        self.doubleSpinBox_hfw.setObjectName("doubleSpinBox_hfw")
        self.gridLayout.addWidget(self.doubleSpinBox_hfw, 2, 1, 1, 1)
        self.label_rate = QtWidgets.QLabel(Form)
        self.label_rate.setObjectName("label_rate")
        self.gridLayout.addWidget(self.label_rate, 4, 0, 1, 1)
        self.doubleSpinBox_rate = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox_rate.setMinimum(0.01)
        self.doubleSpinBox_rate.setSingleStep(0.01)
        self.doubleSpinBox_rate.setObjectName("doubleSpinBox_rate")
        self.gridLayout.addWidget(self.doubleSpinBox_rate, 4, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_depth.setText(_translate("Form", "Depth (um)"))
        self.label_milling_current.setText(_translate("Form", "Current (nA)"))
        self.label_spot_size.setText(_translate("Form", "Spot Size (um)"))
        self.pushButton.setText(_translate("Form", "Show Pattern"))
        self.label_dwell_time.setText(_translate("Form", "Dwell Time (us)"))
        self.label_centre_x.setText(_translate("Form", "Centre X (um)"))
        self.label_pattern.setText(_translate("Form", "Pattern"))
        self.label_title.setText(_translate("Form", "Milling"))
        self.label_centre_y.setText(_translate("Form", "Centre Y (um)"))
        self.label_width.setText(_translate("Form", "Width (um)"))
        self.label_application_file.setText(_translate("Form", "Application File"))
        self.label_height.setText(_translate("Form", "Height (um)"))
        self.label_hfw.setText(_translate("Form", "Horizontal Field Width (um)"))
        self.label_rate.setText(_translate("Form", "Rate (mm3/A/s)"))

