# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ImageSettingsWidget.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(311, 346)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_image_use_autogamma = QtWidgets.QCheckBox(Form)
        self.checkBox_image_use_autogamma.setObjectName("checkBox_image_use_autogamma")
        self.gridLayout.addWidget(self.checkBox_image_use_autogamma, 5, 1, 1, 2)
        self.label_image_hfw = QtWidgets.QLabel(Form)
        self.label_image_hfw.setObjectName("label_image_hfw")
        self.gridLayout.addWidget(self.label_image_hfw, 3, 0, 1, 1)
        self.comboBox_image_beam_type = QtWidgets.QComboBox(Form)
        self.comboBox_image_beam_type.setObjectName("comboBox_image_beam_type")
        self.gridLayout.addWidget(self.comboBox_image_beam_type, 4, 1, 1, 2)
        self.label_image_resolution = QtWidgets.QLabel(Form)
        self.label_image_resolution.setObjectName("label_image_resolution")
        self.gridLayout.addWidget(self.label_image_resolution, 1, 0, 1, 1)
        self.lineEdit_image_path = QtWidgets.QLineEdit(Form)
        self.lineEdit_image_path.setObjectName("lineEdit_image_path")
        self.gridLayout.addWidget(self.lineEdit_image_path, 7, 1, 1, 2)
        self.label_image_beam_type = QtWidgets.QLabel(Form)
        self.label_image_beam_type.setObjectName("label_image_beam_type")
        self.gridLayout.addWidget(self.label_image_beam_type, 4, 0, 1, 1)
        self.doubleSpinBox_image_dwell_time = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox_image_dwell_time.setMaximum(10000000000000.0)
        self.doubleSpinBox_image_dwell_time.setSingleStep(0.01)
        self.doubleSpinBox_image_dwell_time.setProperty("value", 1.0)
        self.doubleSpinBox_image_dwell_time.setObjectName("doubleSpinBox_image_dwell_time")
        self.gridLayout.addWidget(self.doubleSpinBox_image_dwell_time, 2, 1, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 11, 0, 1, 3)
        self.doubleSpinBox_image_hfw = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox_image_hfw.setMaximum(2700.0)
        self.doubleSpinBox_image_hfw.setSingleStep(0.1)
        self.doubleSpinBox_image_hfw.setProperty("value", 150.0)
        self.doubleSpinBox_image_hfw.setObjectName("doubleSpinBox_image_hfw")
        self.gridLayout.addWidget(self.doubleSpinBox_image_hfw, 3, 1, 1, 2)
        self.label_image_dwell_time = QtWidgets.QLabel(Form)
        self.label_image_dwell_time.setObjectName("label_image_dwell_time")
        self.gridLayout.addWidget(self.label_image_dwell_time, 2, 0, 1, 1)
        self.checkBox_image_save_image = QtWidgets.QCheckBox(Form)
        self.checkBox_image_save_image.setObjectName("checkBox_image_save_image")
        self.gridLayout.addWidget(self.checkBox_image_save_image, 6, 0, 1, 1)
        self.label_image_save_path = QtWidgets.QLabel(Form)
        self.label_image_save_path.setObjectName("label_image_save_path")
        self.gridLayout.addWidget(self.label_image_save_path, 7, 0, 1, 1)
        self.label_image_label = QtWidgets.QLabel(Form)
        self.label_image_label.setObjectName("label_image_label")
        self.gridLayout.addWidget(self.label_image_label, 8, 0, 1, 1)
        self.pushButton_take_image = QtWidgets.QPushButton(Form)
        self.pushButton_take_image.setObjectName("pushButton_take_image")
        self.gridLayout.addWidget(self.pushButton_take_image, 9, 0, 1, 3)
        self.spinBox_resolution_y = QtWidgets.QSpinBox(Form)
        self.spinBox_resolution_y.setMinimum(1)
        self.spinBox_resolution_y.setMaximum(999999999)
        self.spinBox_resolution_y.setProperty("value", 1024)
        self.spinBox_resolution_y.setObjectName("spinBox_resolution_y")
        self.gridLayout.addWidget(self.spinBox_resolution_y, 1, 2, 1, 1)
        self.label_title = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.gridLayout.addWidget(self.label_title, 0, 0, 1, 2)
        self.spinBox_resolution_x = QtWidgets.QSpinBox(Form)
        self.spinBox_resolution_x.setMinimum(1)
        self.spinBox_resolution_x.setMaximum(999999999)
        self.spinBox_resolution_x.setProperty("value", 1536)
        self.spinBox_resolution_x.setObjectName("spinBox_resolution_x")
        self.gridLayout.addWidget(self.spinBox_resolution_x, 1, 1, 1, 1)
        self.checkBox_image_use_autocontrast = QtWidgets.QCheckBox(Form)
        self.checkBox_image_use_autocontrast.setChecked(True)
        self.checkBox_image_use_autocontrast.setObjectName("checkBox_image_use_autocontrast")
        self.gridLayout.addWidget(self.checkBox_image_use_autocontrast, 5, 0, 1, 1)
        self.lineEdit_image_label = QtWidgets.QLineEdit(Form)
        self.lineEdit_image_label.setObjectName("lineEdit_image_label")
        self.gridLayout.addWidget(self.lineEdit_image_label, 8, 1, 1, 2)
        self.pushButton_take_all_images = QtWidgets.QPushButton(Form)
        self.pushButton_take_all_images.setObjectName("pushButton_take_all_images")
        self.gridLayout.addWidget(self.pushButton_take_all_images, 10, 0, 1, 3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.checkBox_image_use_autogamma.setText(_translate("Form", "AutoGamma"))
        self.label_image_hfw.setText(_translate("Form", "Horizontal Field Width (um)"))
        self.label_image_resolution.setText(_translate("Form", "Resolution (px)"))
        self.label_image_beam_type.setText(_translate("Form", "Beam Type"))
        self.label_image_dwell_time.setText(_translate("Form", "Dwell Time (us)"))
        self.checkBox_image_save_image.setText(_translate("Form", "Save Image"))
        self.label_image_save_path.setText(_translate("Form", "Path"))
        self.label_image_label.setText(_translate("Form", "Label"))
        self.pushButton_take_image.setText(_translate("Form", "Take Image"))
        self.label_title.setText(_translate("Form", "Image Settings"))
        self.checkBox_image_use_autocontrast.setText(_translate("Form", "AutoContrast"))
        self.pushButton_take_all_images.setText(_translate("Form", "Take All Images"))

