# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ImageSettingsDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(253, 288)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkBox_use_autocontrast = QtWidgets.QCheckBox(self.frame)
        self.checkBox_use_autocontrast.setChecked(True)
        self.checkBox_use_autocontrast.setObjectName("checkBox_use_autocontrast")
        self.gridLayout_2.addWidget(self.checkBox_use_autocontrast, 5, 0, 1, 1)
        self.label_label = QtWidgets.QLabel(self.frame)
        self.label_label.setObjectName("label_label")
        self.gridLayout_2.addWidget(self.label_label, 8, 0, 1, 1)
        self.lineEdit_path = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_path.setObjectName("lineEdit_path")
        self.gridLayout_2.addWidget(self.lineEdit_path, 7, 1, 1, 1)
        self.lineEdit_dwell_time = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_dwell_time.setObjectName("lineEdit_dwell_time")
        self.gridLayout_2.addWidget(self.lineEdit_dwell_time, 3, 1, 1, 1)
        self.label_beam_type = QtWidgets.QLabel(self.frame)
        self.label_beam_type.setObjectName("label_beam_type")
        self.gridLayout_2.addWidget(self.label_beam_type, 1, 0, 1, 1)
        self.label_dwell_time = QtWidgets.QLabel(self.frame)
        self.label_dwell_time.setObjectName("label_dwell_time")
        self.gridLayout_2.addWidget(self.label_dwell_time, 3, 0, 1, 1)
        self.label_hfw = QtWidgets.QLabel(self.frame)
        self.label_hfw.setObjectName("label_hfw")
        self.gridLayout_2.addWidget(self.label_hfw, 4, 0, 1, 1)
        self.pushButton_accept = QtWidgets.QPushButton(self.frame)
        self.pushButton_accept.setObjectName("pushButton_accept")
        self.gridLayout_2.addWidget(self.pushButton_accept, 9, 0, 1, 1)
        self.label_title = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.gridLayout_2.addWidget(self.label_title, 0, 0, 1, 2)
        self.pushButton_cancel = QtWidgets.QPushButton(self.frame)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.gridLayout_2.addWidget(self.pushButton_cancel, 9, 1, 1, 1)
        self.lineEdit_label = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_label.setObjectName("lineEdit_label")
        self.gridLayout_2.addWidget(self.lineEdit_label, 8, 1, 1, 1)
        self.lineEdit_resolution = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_resolution.setObjectName("lineEdit_resolution")
        self.gridLayout_2.addWidget(self.lineEdit_resolution, 2, 1, 1, 1)
        self.comboBox_beam_type = QtWidgets.QComboBox(self.frame)
        self.comboBox_beam_type.setObjectName("comboBox_beam_type")
        self.gridLayout_2.addWidget(self.comboBox_beam_type, 1, 1, 1, 1)
        self.checkBox_use_autogamma = QtWidgets.QCheckBox(self.frame)
        self.checkBox_use_autogamma.setChecked(True)
        self.checkBox_use_autogamma.setObjectName("checkBox_use_autogamma")
        self.gridLayout_2.addWidget(self.checkBox_use_autogamma, 5, 1, 1, 1)
        self.label_path = QtWidgets.QLabel(self.frame)
        self.label_path.setObjectName("label_path")
        self.gridLayout_2.addWidget(self.label_path, 7, 0, 1, 1)
        self.lineEdit_hfw = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_hfw.setObjectName("lineEdit_hfw")
        self.gridLayout_2.addWidget(self.lineEdit_hfw, 4, 1, 1, 1)
        self.label_resolution = QtWidgets.QLabel(self.frame)
        self.label_resolution.setObjectName("label_resolution")
        self.gridLayout_2.addWidget(self.label_resolution, 2, 0, 1, 1)
        self.checkBox_save_image = QtWidgets.QCheckBox(self.frame)
        self.checkBox_save_image.setObjectName("checkBox_save_image")
        self.gridLayout_2.addWidget(self.checkBox_save_image, 6, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.frame)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 10, 0, 1, 2)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.checkBox_use_autocontrast.setText(_translate("Dialog", "Use Autocontrast"))
        self.label_label.setText(_translate("Dialog", "Label"))
        self.lineEdit_dwell_time.setText(_translate("Dialog", "1e-6"))
        self.label_beam_type.setText(_translate("Dialog", "Beam Type"))
        self.label_dwell_time.setText(_translate("Dialog", "Dwell Time"))
        self.label_hfw.setText(_translate("Dialog", "Horizontal Field Width"))
        self.pushButton_accept.setText(_translate("Dialog", "OK"))
        self.label_title.setText(_translate("Dialog", "Image Settings"))
        self.pushButton_cancel.setText(_translate("Dialog", "Cancel"))
        self.lineEdit_resolution.setText(_translate("Dialog", "1536x1024"))
        self.checkBox_use_autogamma.setText(_translate("Dialog", "Use AutoGamma"))
        self.label_path.setText(_translate("Dialog", "Path"))
        self.lineEdit_hfw.setText(_translate("Dialog", "150e-6"))
        self.label_resolution.setText(_translate("Dialog", "Resolution"))
        self.checkBox_save_image.setText(_translate("Dialog", "Save Image"))

