# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MillingUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(391, 358)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox_milling_stage = QtWidgets.QComboBox(Dialog)
        self.comboBox_milling_stage.setObjectName("comboBox_milling_stage")
        self.gridLayout.addWidget(self.comboBox_milling_stage, 3, 1, 1, 1)
        self.label_milling_time = QtWidgets.QLabel(Dialog)
        self.label_milling_time.setObjectName("label_milling_time")
        self.gridLayout.addWidget(self.label_milling_time, 6, 0, 1, 2)
        self.comboBox_select_pattern = QtWidgets.QComboBox(Dialog)
        self.comboBox_select_pattern.setObjectName("comboBox_select_pattern")
        self.gridLayout.addWidget(self.comboBox_select_pattern, 1, 1, 1, 1)
        self.label_milling_stage = QtWidgets.QLabel(Dialog)
        self.label_milling_stage.setObjectName("label_milling_stage")
        self.gridLayout.addWidget(self.label_milling_stage, 3, 0, 1, 1)
        self.label_parameters_header = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_parameters_header.setFont(font)
        self.label_parameters_header.setObjectName("label_parameters_header")
        self.gridLayout.addWidget(self.label_parameters_header, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 10, 0, 1, 2)
        self.pushButton_exit_milling = QtWidgets.QPushButton(Dialog)
        self.pushButton_exit_milling.setObjectName("pushButton_exit_milling")
        self.gridLayout.addWidget(self.pushButton_exit_milling, 8, 1, 1, 1)
        self.comboBox_milling_current = QtWidgets.QComboBox(Dialog)
        self.comboBox_milling_current.setObjectName("comboBox_milling_current")
        self.gridLayout.addWidget(self.comboBox_milling_current, 5, 1, 1, 1)
        self.label_pattern = QtWidgets.QLabel(Dialog)
        self.label_pattern.setObjectName("label_pattern")
        self.gridLayout.addWidget(self.label_pattern, 1, 0, 1, 1)
        self.pushButton_run_milling = QtWidgets.QPushButton(Dialog)
        self.pushButton_run_milling.setObjectName("pushButton_run_milling")
        self.gridLayout.addWidget(self.pushButton_run_milling, 8, 0, 1, 1)
        self.label_milling_current = QtWidgets.QLabel(Dialog)
        self.label_milling_current.setObjectName("label_milling_current")
        self.gridLayout.addWidget(self.label_milling_current, 5, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout.addLayout(self.gridLayout_2, 4, 0, 1, 2)
        self.label_title = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.gridLayout.addWidget(self.label_title, 0, 0, 1, 2)
        self.label_message = QtWidgets.QLabel(Dialog)
        self.label_message.setMinimumSize(QtCore.QSize(0, 50))
        self.label_message.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_message.setWordWrap(True)
        self.label_message.setObjectName("label_message")
        self.gridLayout.addWidget(self.label_message, 7, 0, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_milling_time.setText(_translate("Dialog", "Estimated Time: "))
        self.label_milling_stage.setText(_translate("Dialog", "Milling Stage"))
        self.label_parameters_header.setText(_translate("Dialog", "Milling Parameters"))
        self.pushButton_exit_milling.setText(_translate("Dialog", "Exit"))
        self.label_pattern.setText(_translate("Dialog", "Pattern"))
        self.pushButton_run_milling.setText(_translate("Dialog", "Run Milling"))
        self.label_milling_current.setText(_translate("Dialog", "Milling Current (nA)"))
        self.label_title.setText(_translate("Dialog", "Milling"))
        self.label_message.setText(_translate("Dialog", "TextLabel"))
