# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'movement_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1288, 691)
        self.frame_main = QtWidgets.QFrame(Dialog)
        self.frame_main.setGeometry(QtCore.QRect(10, 10, 1261, 661))
        self.frame_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main.setObjectName("frame_main")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_main)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_image = QtWidgets.QFrame(self.frame_main)
        self.frame_image.setMaximumSize(QtCore.QSize(1536, 1024))
        self.frame_image.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_image.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_image.setObjectName("frame_image")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_image)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_image_eb = QtWidgets.QLabel(self.frame_image)
        self.label_image_eb.setText("")
        self.label_image_eb.setObjectName("label_image_eb")
        self.gridLayout_3.addWidget(self.label_image_eb, 0, 0, 1, 1)
        self.label_image_ib = QtWidgets.QLabel(self.frame_image)
        self.label_image_ib.setText("")
        self.label_image_ib.setObjectName("label_image_ib")
        self.gridLayout_3.addWidget(self.label_image_ib, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frame_image, 1, 1, 2, 1)
        self.label_title = QtWidgets.QLabel(self.frame_main)
        self.label_title.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setTextFormat(QtCore.Qt.PlainText)
        self.label_title.setObjectName("label_title")
        self.gridLayout_2.addWidget(self.label_title, 0, 0, 1, 2)
        self.frame_base = QtWidgets.QFrame(self.frame_main)
        self.frame_base.setMaximumSize(QtCore.QSize(16777215, 125))
        self.frame_base.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_base.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_base.setObjectName("frame_base")
        self.label_message = QtWidgets.QLabel(self.frame_base)
        self.label_message.setGeometry(QtCore.QRect(16, 12, 1011, 125))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_message.sizePolicy().hasHeightForWidth())
        self.label_message.setSizePolicy(sizePolicy)
        self.label_message.setMaximumSize(QtCore.QSize(16777215, 125))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_message.setFont(font)
        self.label_message.setAlignment(QtCore.Qt.AlignCenter)
        self.label_message.setObjectName("label_message")
        self.gridLayout_2.addWidget(self.frame_base, 3, 1, 1, 1)
        self.frame_parameters = QtWidgets.QFrame(self.frame_main)
        self.frame_parameters.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_parameters.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_parameters.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_parameters.setObjectName("frame_parameters")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_parameters)
        self.gridLayout_4.setVerticalSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton_continue = QtWidgets.QPushButton(self.frame_parameters)
        self.pushButton_continue.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_continue.setObjectName("pushButton_continue")
        self.gridLayout_4.addWidget(self.pushButton_continue, 33, 1, 1, 2)
        self.doubleSpinBox_hfw = QtWidgets.QDoubleSpinBox(self.frame_parameters)
        self.doubleSpinBox_hfw.setMinimum(30.0)
        self.doubleSpinBox_hfw.setMaximum(900.0)
        self.doubleSpinBox_hfw.setSingleStep(5.0)
        self.doubleSpinBox_hfw.setProperty("value", 150.0)
        self.doubleSpinBox_hfw.setObjectName("doubleSpinBox_hfw")
        self.gridLayout_4.addWidget(self.doubleSpinBox_hfw, 2, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 26, 1, 1, 2)
        self.label_movement_mode = QtWidgets.QLabel(self.frame_parameters)
        self.label_movement_mode.setObjectName("label_movement_mode")
        self.gridLayout_4.addWidget(self.label_movement_mode, 20, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_4.addItem(spacerItem1, 32, 1, 1, 2)
        self.label_1 = QtWidgets.QLabel(self.frame_parameters)
        self.label_1.setObjectName("label_1")
        self.gridLayout_4.addWidget(self.label_1, 2, 1, 1, 1)
        self.pushButton_take_image = QtWidgets.QPushButton(self.frame_parameters)
        self.pushButton_take_image.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_take_image.setObjectName("pushButton_take_image")
        self.gridLayout_4.addWidget(self.pushButton_take_image, 3, 1, 1, 2)
        self.label_header_movement = QtWidgets.QLabel(self.frame_parameters)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_header_movement.setFont(font)
        self.label_header_movement.setObjectName("label_header_movement")
        self.gridLayout_4.addWidget(self.label_header_movement, 18, 1, 1, 2)
        self.label_continue_instructions = QtWidgets.QLabel(self.frame_parameters)
        self.label_continue_instructions.setMinimumSize(QtCore.QSize(0, 40))
        self.label_continue_instructions.setTextFormat(QtCore.Qt.AutoText)
        self.label_continue_instructions.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_continue_instructions.setWordWrap(True)
        self.label_continue_instructions.setObjectName("label_continue_instructions")
        self.gridLayout_4.addWidget(self.label_continue_instructions, 30, 1, 2, 2)
        self.label_header = QtWidgets.QLabel(self.frame_parameters)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_header.setFont(font)
        self.label_header.setObjectName("label_header")
        self.gridLayout_4.addWidget(self.label_header, 1, 1, 1, 2)
        self.comboBox_movement_mode = QtWidgets.QComboBox(self.frame_parameters)
        self.comboBox_movement_mode.setObjectName("comboBox_movement_mode")
        self.gridLayout_4.addWidget(self.comboBox_movement_mode, 20, 2, 1, 1)
        self.label_header_tilt = QtWidgets.QLabel(self.frame_parameters)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_header_tilt.setFont(font)
        self.label_header_tilt.setObjectName("label_header_tilt")
        self.gridLayout_4.addWidget(self.label_header_tilt, 21, 1, 1, 1)
        self.label_tilt = QtWidgets.QLabel(self.frame_parameters)
        self.label_tilt.setObjectName("label_tilt")
        self.gridLayout_4.addWidget(self.label_tilt, 22, 1, 1, 1)
        self.doubleSpinBox_tilt_degrees = QtWidgets.QDoubleSpinBox(self.frame_parameters)
        self.doubleSpinBox_tilt_degrees.setDecimals(0)
        self.doubleSpinBox_tilt_degrees.setMinimum(0.0)
        self.doubleSpinBox_tilt_degrees.setMaximum(25.0)
        self.doubleSpinBox_tilt_degrees.setSingleStep(1.0)
        self.doubleSpinBox_tilt_degrees.setProperty("value", 0.0)
        self.doubleSpinBox_tilt_degrees.setObjectName("doubleSpinBox_tilt_degrees")
        self.gridLayout_4.addWidget(self.doubleSpinBox_tilt_degrees, 22, 2, 1, 1)
        self.pushButton_tilt_stage = QtWidgets.QPushButton(self.frame_parameters)
        self.pushButton_tilt_stage.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_tilt_stage.setObjectName("pushButton_tilt_stage")
        self.gridLayout_4.addWidget(self.pushButton_tilt_stage, 24, 1, 1, 2)
        self.gridLayout_2.addWidget(self.frame_parameters, 1, 0, 3, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_title.setText(_translate("Dialog", "AutoLiftout Movement"))
        self.label_message.setText(_translate("Dialog", "TextLabel"))
        self.pushButton_continue.setText(_translate("Dialog", "Continue"))
        self.label_movement_mode.setText(_translate("Dialog", "Mode"))
        self.label_1.setText(_translate("Dialog", "Horizontal Field Width"))
        self.pushButton_take_image.setText(_translate("Dialog", "Take New Image"))
        self.label_header_movement.setText(_translate("Dialog", "Movement Settings"))
        self.label_continue_instructions.setText(_translate("Dialog", "Double click to move. \n"
"Press continue when complete."))
        self.label_header.setText(_translate("Dialog", "Image Settings"))
        self.label_header_tilt.setText(_translate("Dialog", "Tilt Settings"))
        self.label_tilt.setText(_translate("Dialog", "Stage Tilt (Degrees)"))
        self.pushButton_tilt_stage.setText(_translate("Dialog", "Tilt Stage"))

