# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NapariMilling.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(310, 881)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(400, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_milling_depth = QtWidgets.QLabel(self.frame)
        self.label_milling_depth.setObjectName("label_milling_depth")
        self.gridLayout_2.addWidget(self.label_milling_depth, 5, 0, 1, 2)
        self.doubleSpinBox_milling_depth = QtWidgets.QDoubleSpinBox(self.frame)
        self.doubleSpinBox_milling_depth.setMinimum(0.1)
        self.doubleSpinBox_milling_depth.setMaximum(1000.0)
        self.doubleSpinBox_milling_depth.setSingleStep(0.1)
        self.doubleSpinBox_milling_depth.setProperty("value", 2.0)
        self.doubleSpinBox_milling_depth.setObjectName("doubleSpinBox_milling_depth")
        self.gridLayout_2.addWidget(self.doubleSpinBox_milling_depth, 5, 2, 1, 1)
        self.comboBox_pattern_type = QtWidgets.QComboBox(self.frame)
        self.comboBox_pattern_type.setObjectName("comboBox_pattern_type")
        self.gridLayout_2.addWidget(self.comboBox_pattern_type, 4, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 10, 0, 1, 3)
        self.doubleSpinBox_imaging_hfw = QtWidgets.QDoubleSpinBox(self.frame)
        self.doubleSpinBox_imaging_hfw.setMinimum(10.0)
        self.doubleSpinBox_imaging_hfw.setMaximum(900.0)
        self.doubleSpinBox_imaging_hfw.setProperty("value", 150.0)
        self.doubleSpinBox_imaging_hfw.setObjectName("doubleSpinBox_imaging_hfw")
        self.gridLayout_2.addWidget(self.doubleSpinBox_imaging_hfw, 1, 2, 1, 1)
        self.comboBox_milling_current = QtWidgets.QComboBox(self.frame)
        self.comboBox_milling_current.setObjectName("comboBox_milling_current")
        self.gridLayout_2.addWidget(self.comboBox_milling_current, 6, 2, 1, 1)
        self.label_milling_current = QtWidgets.QLabel(self.frame)
        self.label_milling_current.setObjectName("label_milling_current")
        self.gridLayout_2.addWidget(self.label_milling_current, 6, 0, 1, 2)
        self.label_title = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.gridLayout_2.addWidget(self.label_title, 0, 0, 1, 3)
        self.pushButton_update_milling_pattern = QtWidgets.QPushButton(self.frame)
        self.pushButton_update_milling_pattern.setObjectName("pushButton_update_milling_pattern")
        self.gridLayout_2.addWidget(self.pushButton_update_milling_pattern, 7, 0, 1, 3)
        self.label_imaging_hfw = QtWidgets.QLabel(self.frame)
        self.label_imaging_hfw.setObjectName("label_imaging_hfw")
        self.gridLayout_2.addWidget(self.label_imaging_hfw, 1, 0, 1, 1)
        self.label_pattern_type = QtWidgets.QLabel(self.frame)
        self.label_pattern_type.setObjectName("label_pattern_type")
        self.gridLayout_2.addWidget(self.label_pattern_type, 4, 0, 1, 2)
        self.pushButton_take_image = QtWidgets.QPushButton(self.frame)
        self.pushButton_take_image.setObjectName("pushButton_take_image")
        self.gridLayout_2.addWidget(self.pushButton_take_image, 2, 0, 1, 3)
        self.pushButton_run_milling = QtWidgets.QPushButton(self.frame)
        self.pushButton_run_milling.setObjectName("pushButton_run_milling")
        self.gridLayout_2.addWidget(self.pushButton_run_milling, 9, 0, 1, 3)
        self.label_milling_header = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_milling_header.setFont(font)
        self.label_milling_header.setObjectName("label_milling_header")
        self.gridLayout_2.addWidget(self.label_milling_header, 3, 0, 1, 3)
        self.label_milling_estimated_time = QtWidgets.QLabel(self.frame)
        self.label_milling_estimated_time.setObjectName("label_milling_estimated_time")
        self.gridLayout_2.addWidget(self.label_milling_estimated_time, 8, 0, 1, 3)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 310, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_milling_depth.setText(_translate("MainWindow", "Depth (um)"))
        self.label_milling_current.setText(_translate("MainWindow", "Milling Current (A)"))
        self.label_title.setText(_translate("MainWindow", "Napari Milling"))
        self.pushButton_update_milling_pattern.setText(_translate("MainWindow", "Update Milling Pattern"))
        self.label_imaging_hfw.setText(_translate("MainWindow", "HFW (um)"))
        self.label_pattern_type.setText(_translate("MainWindow", "Pattern Type"))
        self.pushButton_take_image.setText(_translate("MainWindow", "Take Image"))
        self.pushButton_run_milling.setText(_translate("MainWindow", "Run Milling"))
        self.label_milling_header.setText(_translate("MainWindow", "Milling Settings"))
        self.label_milling_estimated_time.setText(_translate("MainWindow", "Estimated Time: 99999"))

