wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1662942920.933463
    t:
      1:
      - 1
      - 41
      - 54
      - 55
      - 63
      - 74
      3:
      - 23
      4: 3.9.13
      5: 0.13.2
      8:
      - 3
      - 5
