name: docs
on:
  push:
    branches:
      - v0.2-stable
  pull_request:
    branches:
      - v0.2-release
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mkdocstrings-python
      - run: mkdocs gh-deploy --force
